# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

cache: pip

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - pip install numpy fitsio pytest
    - pip install coverage
    - pip install -e .

script: py.test testing

after_success:
    # Upload coverage to codecov.io
      - bash <(curl -s https://codecov.io/bash)
